# Generated by Django 3.1.3 on 2021-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('area', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=11)),
            ],
            options={
                'unique_together': {('name', 'contact')},
            },
        ),
    ]
